export const SITE={name:'PakCalc Hub',url:'https://pakcalchub.com'};
export const TOOLS=[
{slug:'comsats-gpa-calculator',name:'COMSATS GPA Calculator',cat:'Education',title:'COMSATS GPA Calculator 2026 – Semester GPA & Grade Points (Free)',h1:'COMSATS GPA Calculator',
desc:'Free COMSATS GPA calculator using the CUI 4.0 grade-point scale. Add courses, credit hours and grades to get your semester GPA instantly.',
intro:'Use this COMSATS GPA calculator to find your semester GPA in seconds. Select the grade for each course, enter credit hours, and the tool multiplies grade points by credit hours and divides by total credits.',
steps:['Enter each course name (optional).','Pick the grade you received from A to F.','Enter the course credit hours (usually 1 to 4).','Press Calculate GPA to see your GPA and total quality points.'],
faq:[['How is COMSATS GPA calculated?','GPA = sum of (grade points x credit hours) divided by total credit hours of the semester.'],['What is the maximum GPA at COMSATS?','The maximum is 4.00, earned with an A grade in every course.'],['How do I calculate CGPA at COMSATS?','Use our CGPA calculator: enter each semester GPA with its credit hours.']]},
{slug:'gpa-calculator',name:'GPA Calculator',cat:'Education',title:'GPA Calculator – Free Semester GPA Calculator for Pakistani Universities',h1:'GPA Calculator (4.0 Scale)',
desc:'Free universal GPA calculator on the 4.0 scale. Works for most Pakistani universities using letter grades. Instant results.',
intro:'This universal GPA calculator works with the standard 4.0 letter-grade scale. Add your subjects, choose grades, enter credit hours and get your GPA instantly.',
steps:['Add a row for every subject.','Choose the letter grade.','Enter credit hours.','Click Calculate GPA.'],
faq:[['What is a good GPA?','A GPA of 3.0 or above is generally considered good; 3.5+ is excellent for scholarships.'],['Is this the same for every university?','Most use the 4.0 scale, but grade cut-offs differ. Always confirm with your university handbook.']]},
{slug:'cgpa-calculator',name:'CGPA Calculator',cat:'Education',title:'CGPA Calculator – Calculate Cumulative GPA from Semester GPAs',h1:'CGPA Calculator',
desc:'Free CGPA calculator. Enter each semester GPA and credit hours to calculate your cumulative GPA for your degree.',
intro:'CGPA is the weighted average of all your semester GPAs. Enter every semester GPA with its credit hours below.',
steps:['Enter semester GPA.','Enter total credit hours of that semester.','Add more semesters.','Click Calculate CGPA.'],
faq:[['How to calculate CGPA?','CGPA = sum of (semester GPA x semester credits) / total credits.'],['CGPA vs GPA?','GPA covers one semester; CGPA covers your whole degree so far.']]},
{slug:'percentage-calculator',name:'Percentage & Marks Calculator',cat:'Education',title:'Percentage Calculator – Marks Percentage & Percent of a Number',h1:'Percentage & Marks Calculator',
desc:'Free percentage calculator. Find marks percentage and what percent of a number is, instantly.',
intro:'Calculate your marks percentage or find any percentage of a number quickly.',
steps:['Enter obtained marks and total marks.','See the percentage.','Or use the second box to find X% of a number.'],
faq:[['How to calculate marks percentage?','Percentage = (obtained marks / total marks) x 100.'],['How to find X% of a number?','Multiply the number by X and divide by 100.']]},
{slug:'salary-increment-calculator',name:'Salary Increment Calculator',cat:'Finance',title:'Salary Increment Calculator – New Salary After % Raise (Pakistan)',h1:'Salary Increment Calculator',
desc:'Free salary increment calculator. Enter current salary and raise percentage to see new monthly and yearly salary in PKR.',
intro:'Find out your new salary after an annual increment. Works in PKR or any currency.',
steps:['Enter your current monthly salary.','Enter increment percentage.','See new monthly and yearly salary.'],
faq:[['How is salary increment calculated?','New salary = current salary x (1 + increment% / 100).'],['Does this include tax?','No. This shows gross salary. Tax depends on the current FBR slabs.']]},
{slug:'zakat-calculator',name:'Zakat Calculator',cat:'Finance',title:'Zakat Calculator – Calculate 2.5% Zakat on Cash, Gold & Business',h1:'Zakat Calculator',
desc:'Free zakat calculator. Add cash, gold, silver, business assets and debts to calculate zakat at 2.5% against the nisab.',
intro:'Zakat is 2.5% of eligible wealth held for one lunar year above the nisab. Enter the current nisab value (silver-based is commonly used) and your assets in PKR.',
steps:['Enter the current nisab value in PKR.','Enter cash, gold, silver, investments and business stock.','Enter debts you owe.','Press Calculate Zakat.'],
faq:[['What is the zakat rate?','2.5% of net zakatable wealth.'],['What is nisab?','The minimum wealth threshold. Check the current silver or gold price and confirm with a scholar.']]},
{slug:'age-calculator',name:'Age Calculator',cat:'Utility',title:'Age Calculator – Exact Age in Years, Months & Days',h1:'Age Calculator',
desc:'Free age calculator. Enter your date of birth to get exact age in years, months, days and days until next birthday.',
intro:'Get your exact age from date of birth, useful for job and admission form eligibility.',
steps:['Select date of birth.','Optionally change the "age at" date.','See your exact age.'],
faq:[['How is age calculated?','Age is the difference between the target date and date of birth in years, months and days.']]},
{slug:'discount-calculator',name:'Discount / Sale Calculator',cat:'Finance',title:'Discount Calculator – Final Price After Sale Percentage',h1:'Discount / Sale Calculator',
desc:'Free discount calculator. Enter price and discount percent to get final price and amount saved.',
intro:'Quickly find the sale price and how much you save.',
steps:['Enter original price.','Enter discount percent.','See final price and savings.'],
faq:[['How to calculate a discount?','Final price = price - (price x discount / 100).']]},
{slug:'area-converter',name:'Area Converter (Marla, Kanal)',cat:'Converters',title:'Area Converter – Marla, Kanal, Acre, Square Feet Converter',h1:'Area Converter',
desc:'Convert marla, kanal, square feet, square yards, acres and square meters instantly.',intro:'Pakistani land units made easy. This tool uses 1 marla = 272.25 sq ft and 1 kanal = 20 marla.',
steps:['Enter a value.','Choose from-unit and to-unit.'],faq:[['1 kanal is how many marla?','20 marla.'],['1 marla in square feet?','272.25 square feet (standard).']]},
{slug:'weight-converter',name:'Weight Converter (Tola, Seer, Maund)',cat:'Converters',title:'Weight Converter – Tola, Seer, Maund, KG, Pound Converter',h1:'Weight Converter',
desc:'Convert tola, seer, maund, kg, gram, pound and ounce. Ideal for gold and grain.',intro:'Convert between metric and Pakistani traditional weights.',
steps:['Enter a value.','Choose units.'],faq:[['1 tola in grams?','About 11.66 grams.'],['1 maund in kg?','About 37.32 kg.']]},
{slug:'length-converter',name:'Length Converter',cat:'Converters',title:'Length Converter – Feet, Inches, Meters, KM, Miles',h1:'Length Converter',
desc:'Convert feet, inches, cm, meters, km, yards and miles.',intro:'Simple length conversion.',steps:['Enter a value.','Choose units.'],faq:[['1 foot in cm?','30.48 cm.']]},
{slug:'temperature-converter',name:'Temperature Converter',cat:'Converters',title:'Temperature Converter – Celsius, Fahrenheit, Kelvin',h1:'Temperature Converter',
desc:'Convert Celsius, Fahrenheit and Kelvin instantly.',intro:'Convert temperature between scales.',steps:['Enter a value.','Choose units.'],faq:[['C to F formula?','F = C x 9/5 + 32.']]},
{slug:'word-counter',name:'Word & Character Counter',cat:'Utility',title:'Word Counter – Count Words, Characters & Reading Time Online',h1:'Word & Character Counter',
desc:'Free online word counter. Count words, characters and reading time.',intro:'Paste your text to count words and characters instantly.',steps:['Paste or type text.','See live counts.'],faq:[['Does it count spaces?','Both with and without spaces are shown.']]}
];
